# Generated by Django 3.2.18 on 2023-03-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglist',
            old_name='tittle',
            new_name='title',
        ),
    ]
